#!/usr/bin/env bash
set -euo pipefail

# Install vendored Ruby dependencies locally.
# Usage: script/bootstrap

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${HERE}/env" "$@"

cd "${DIR}"
bundle install --local
bundle binstubs --all
